### ISSUE TITLE
Missing commands in autocompletion

### ISSUE THREAD

**Issue by exploide** [James-Yu/Atom-LaTeX#10]
I noticed there are some commands missing from autocompletion. These include
- \subsection
- \textit
- \texttt
and probably others.

Beside these well-known standard commands, is it possible to figure out what additional commands become available from `\usepackage` declarations? An example would be that when `\usepackage{csquotes}` is present, `\enquote{...}` becomes a valid autocompletion.
I know, the latter is probably more complicated but I guess this would be an awesome feature.

**Comment by James-Yu** [comment]
Answers to the two questions.
- Now the plugin "learns" from what you input in tex files. If a command appeared at any tex files in your latex project, the plugin will show autocomplete for it. I agree that there are some necessary ones and I will consider adding them. But the list will not be very long.

- Short answer is: no, it is not possible due to the infamous latex language design. Detailed explanation can be found in [this link](http://tex.stackexchange.com/questions/283262/how-to-get-a-list-of-valid-commands). Another work around is to manual list commands for each packages. However as there are more than 4k (or significantly more) packages, it's a very tedious task.

I will close this issue for now. If you find something wrong or have other suggestions, please feel free to re-open it or create a new one. :p

**Comment by exploide** [comment]
I expected something like this for the second question :P too bad.

But yes, I think you are right that the most important commands which are considered "standard" are worth adding.
