### ISSUE TITLE
Can't get SyncTeX to work

### ISSUE THREAD

**Issue by urigrupel** [James-Yu/Atom-LaTeX#114]
Hi,

I'm thinking about moving from TexStudio to Atom as my latex editor. The problem is I can't get the synctex functions to work. This is for me a key feature.

I use windows 10 64bit, with miktex 2.9. The toolchain is texify (I copied the toolchain command).
I added "% !TEX root = sampling.tex" to the top of my file.

After I compile, I don't have any option to go back to the source from the pdf. When I try to go from the source to the pdf I get "Failed SyncTex (code 3221225781)"
Command failed: synctex view -i "216:25:C:\Users\...\sampling.tex" -o "C:\Users\...\sampling.pdf"
Also, the compiled pdf is always shown from the top, and not from the last place my cursor was on.

What am I doing wrong?

Thanks,
Uri

**Comment by ashthespy** [comment]
Hi,
Syntex with MikTeX needs some additional `dll` files to work. Try grabbing the binaries directly from the [TexLive svn](https://www.tug.org/svn/texlive/trunk/Master/bin/win32/)

You can grab the following files and place them directly in `\MiKTeX 2.9\miktex\bin\x64`
1. [`synctex.exe`](https://www.tug.org/svn/texlive/trunk/Master/bin/win32/synctex.exe?revision=44054&view=co) 
2. [`kpathseaxxx.dll`](https://www.tug.org/svn/texlive/trunk/Master/bin/win32/kpathsea623.dll?revision=43972&view=co) 

If that doesn't work - have a look at [another possible suggestion](https://github.com/James-Yu/LaTeX-Workshop/issues/106#issuecomment-293141892)

**Comment by urigrupel** [comment]
Thank you for the quick reply!

I forgot to mention in my first post that I did copy those files to my miktex folder.

I had an older version of the dll, and it seems that that was my problem. Now almost everything works well. When I compile the pdf is shown in the correct place, and I can jump back from the pdf to the source. I still cannot jump from source to pdf (unless I just compile again), do you know anything about this problem?

Anyway, I have the main functionality I was looking for!
Thank you so much,
Uri

**Comment by ashthespy** [comment]
Sure thing :-) 
Unfortunately, I can't update my original stackexchange answer any longer - should update the readme here..

For Tex--> Pdf  synctex the command is mapped to <kbd>`ctrl`</kbd>+<kbd>`L`</kbd> <kbd>`ctrl`</kbd>+<kbd>`S`</kbd> or found in the right click menu.

**Comment by urigrupel** [comment]
Thank you, I know how to activate this command, I meant to say that it doesn't work when I use it.
I don't get any errors but nothing happens.

**Comment by ashthespy** [comment]
Could you check if they are any errors thrown in the Dev console (<kbd>`ctrl`</kbd>+<kbd>`shift`</kbd>+<kbd>`i`</kbd>)

**Comment by urigrupel** [comment]
There is an error message:
Uncaught TypeError: Cannot read property 'viewport' of undefined
    at WebSocket.socket.addEventListener (latex.js:22)
socket.addEventListener @ latex.js:22

**Comment by ashthespy** [comment]
Yes, this is what I have been witnessing of late as well. 
However, I believe this is more an upstream error, with synctex and how an improper/missing  `synctex.gz` file is parsed. 

Could you try running:
`synctex view -i "<AtomEditorRowNumber>:<AtomEditorColumn Number>:path/to/file.tex" -o "path/to/file.pdf"` from the command line, and post you output?
I normally get only `This is SyncTeX command line utility, version 1.3` instead of the actual output/error. 

I shall add some checking to throw a warning from the package for this case, but the actual issue is with the generation/parsing of the `synctex.gz` by the compilation - which is outside the scope of this issue!

**Comment by urigrupel** [comment]
Hi,
I hope I understood you correctly. I went to the windows command prompt, went to the project folder and ran the command. Atom and the preview of my project were open. If you meant for me to do something else, please let me know and I'll try it.
I got:
This is SyncTeX command line utility, version 1.3
SyncTeX Warning: No tag for sampling.tex

Maybe it is a problem with synctex.
Thanks for all your help,
Uri

**Comment by ashthespy** [comment]
Thanks, as suspected - seems more an SynTeX, compilation issue. 
I dunno what compiler toolchain you are using, but you need to probably dig a bit into that that figure out why you have no SynTeX tags!

From the package point of view, I shall add a warning.

**Comment by urigrupel** [comment]
Thanks for all your help! 
If I'll find the problem I'll update you.

**Comment by CSpaccasassi** [comment]
Hi, I'm having the same issue as urigrupel, except that it's in Latex Workshop (luckily they are developed by the same person :) ). The problem seems to be that SyncTex is very peculiar about the path it's fed. Just passing file.tex and file.pdf doesn't work:
```
$ synctex view -i "103:1:file.tex" -o file.pdf
This is SyncTeX command line utility, version 1.3
SyncTeX Warning: No tag for file.tex
```
If I pass the full path to the tex file, plus an extra ".\\" for some reason, it does work:
```
$ synctex view -i "1:103:C:\full\path\to\.\file.tex" -o file.pdf
This is SyncTeX command line utility, version 1.3
SyncTeX result begin
...
```
then it works (I'm on Windows by the way). I found out about this (IMO bizarre) behaviour [here](https://tex.stackexchange.com/questions/25578/why-is-synctex-in-tl-2011-so-fussy-about-filenames).

Sorry for cross linking to another tool, but does this might be relevant for both Latex Workshop and Atom. Does Latex Workshop already support this way of referencing tex files?

**Comment by ashthespy** [comment]
@CSpaccasassi Thanks for the information - I will explore a bit!
Can you try updating your `SyncTeX ` version? I don't seem to have this issue running `version 1.18`

**Comment by CSpaccasassi** [comment]
Thanks! I believe I'm running the latest version, I've downloaded SyncTeX from the tug archives a couple of days ago as per [here](https://tex.stackexchange.com/questions/338078/how-to-get-synctex-for-windows-to-allow-atom-pdf-view-to-synch). This is the version number I get from my prompt:
```
$ synctex help
This is SyncTeX command line utility, version 1.3
usage: synctex <subcommand> [options] [args]
Synchronize TeXnology command-line client, version 1.18
...
```
