### ISSUE TITLE
Why so many releases?

### ISSUE THREAD

**Issue by nuskorpios** [James-Yu/Atom-LaTeX#13]
First of all, thanks for this package; it eased my life a lot.

With that being said, here's my question: why so many frequent releases? I had to update atom-latex many times just this week. Frequent releases may be good, as it shows the package is not dead and is maintained, but it is annoying &mdash; at least, for me &mdash; have to update the package once every two days, more or less.

Isn't it more convenient to make a trace of all bug fixed, minor and major changes, putting it into README maybe, and prepare new releases in a larger gap in between, say two, three weeks?

Regards,
Emerson

**Comment by James-Yu** [comment]
Changes are listed in the `changelog` file.

**Comment by James-Yu** [comment]
As to the frequent updates (I would prefer naming them updates instead of releases), I am sure it is really dependent on devs' styles. Despite that, I will consider having weekly updates unless critical fixes. I've not thought of that a part of the userbase would prefer stable and relatively slow update paces. Learnt a new lesson.

**Comment by nuskorpios** [comment]
Thank you for the kind response. It'll be great to have updates within a regular schedule.

For the records, when I wrote the issue, I've wrote "update" instead of "release", but I thought *maybe* I was wrong. I was wrong about thinking I was wrong :smile: 

Again, thanks.
