### ISSUE TITLE
Automatic detection of bibtex usage

### ISSUE THREAD

**Issue by apeltzer** [James-Yu/Atom-LaTeX#15]
Hi! 

changing the custom toolchain for each document in the settings is not really the way things should work. This custom toolchain works for my document without bibliography (thus no bibtex needs to be run), but fails of course for a document with bibtex output. Can't we have something to check whether bibtex needs to be run in all cases? 

<img width="896" alt="screen shot 2017-03-05 at 16 29 15" src="https://cloud.githubusercontent.com/assets/2359510/23588649/eae4ca9c-01c0-11e7-9223-c4a2b0d81eef.png">

**Comment by James-Yu** [comment]
I would recommend you have a check on [`latexmk`](https://www.ctan.org/pkg/latexmk/?lang=en), which serves your need perfectly.

It is technically hard to detect if bibtex is needed or not due to the extremely complex latex command definitions. You can refer to [this](http://tex.stackexchange.com/questions/94106/all-latex-commands-list) and [this](http://tex.stackexchange.com/questions/283262/how-to-get-a-list-of-valid-commands) for more information.

The best alternative is to set a per-project toolchain setting using magic comment or `.latexcfg` file, which is a to-do.

**Comment by apeltzer** [comment]
Hmm, still not working - all packages are installed though... I guess that the way atom starts shell scripts, the PATH variables are not passed on properly.

`
Running 'latex  -recorder  "0_PraktikumPlan.tex"'
------------
sh: latex: command not found
`
(although MacTex 2016 is installed, all tools can be called from iTerm/Terminal, but not from atom)... 

However, if I open up a terminal, start atom from there, the PATH is exported and I can successfully build using auto/latexmk (whatever I want, as before!). 

This is a bit weird, and not necessarily something you can fix in your plugin, but maybe others will stumble upon this, too.

**Comment by James-Yu** [comment]
Thanks for the comments, they are very valuable for Mac dev.

As a temporary work-around, you can change your setting based on your screenshot as follows:

compiler to use: change/this/to/path/to/latexmk
compiling parameters: append a `-pdf` to the default one
toolchain to use: custom

This should work just the same as calling `latexmk` from terminal.
