### ISSUE TITLE
Uncaught TypeError: atom.workspace.paneForItem(...).activeItem.updateTitle is not a function

### ISSUE THREAD

**Issue by Olivia-Vasquez** [James-Yu/Atom-LaTeX#191]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Mac OS X 10.14.3
**Thrown From**: [atom-latex](https://github.com/James-Yu/Atom-LaTeX) package 0.8.5

### Stack Trace

Uncaught TypeError: atom.workspace.paneForItem(...).activeItem.updateTitle is not a function

```
At /Users/oliviavasquez/.atom/packages/atom-latex/lib/viewer.coffee:40

TypeError: atom.workspace.paneForItem(...).activeItem.updateTitle is not a function
    at Viewer.module.exports.Viewer.refresh (/packages/atom-latex/lib/viewer.coffee:40:55)
    at Builder.module.exports.Builder.postBuild (/packages/atom-latex/lib/builder.coffee:123:21)
    at Builder.module.exports.Builder.buildProcess (/packages/atom-latex/lib/builder.coffee:45:8)
    at /packages/atom-latex/lib/builder.coffee:77:10)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

### Commands

```
     -1:55.5.0 application:open (webview.)
     -0:35.2.0 core:save (input.hidden-input)
  4x -0:34.3.0 atom-latex:build (input.hidden-input)
  9x -0:29.4.0 core:save (input.hidden-input)
  8x -0:14.7.0 atom-latex:build (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.16 
atom-latex 0.8.5 
script 3.18.1 
wordcount 3.0.0 
```

**Comment by ashthespy** [comment]
Please fill in steps to reproduce so that the issue can be debugged!

**Comment by ashthespy** [comment]
Closing this for now, feel free to chime in to reopen this..

**Comment by fiee** [comment]
I got this error when I changed the root document, but left the pdf viewer tab open, then hit compile.
After closing the pdf viewer, it worked again.

**Comment by marcschulder** [comment]
It appears to me the issue occurs when Atom-LaTeX has to change the input source while the Build-PDF is not a visible tab.

Steps to reproduce:
1. Open two documents with different root documents (in my case the documents themselves, but also explicitly defined via magic line)
2. Build document A, so that view is split between documents (left view) and Build-PDF (right view)
3. Open a third document on the **right view**, so that the Build-PDF is open but hidden.
4. Select document B (the one not on build-focus right now).
5. Call "Build LaTeX from active editor" then raises the exception.
6. From this point onwards **any** build call will cause this exception as long as the Build-PDF is a hidden tab. Problem is fixed by making the Build-PDF tab visible or closing it.

**Comment by ashthespy** [comment]
Found the issue, should be fixed in the next release.

**Comment by marcschulder** [comment]
I can confirm that this fixed it for me. Thanks!
