### ISSUE TITLE
stdout maxBuffer exceeded when compiling

### ISSUE THREAD

**Issue by rvalkass** [James-Yu/Atom-LaTeX#5]
When compiling my LaTeX file with latexmk through Atom, the compilation fails with the error message "stdout maxBuffer exceeded". Admittedly this is a large compilation, but it runs perfectly fine using latexmk from the command line.

I'm guessing atom-latex is attempting to read the entire compilation output in one massive chunk, rather than streaming it line by line?

**Comment by James-Yu** [comment]
According to [this link](http://stackoverflow.com/questions/23429499/stdout-buffer-issue-using-node-child-process) the maximum buffer size is 200kb, which should be fine for most projects. Can you please provide more info on your log, e.g., file size and number of lines? I am looking into the issue now.

**Comment by James-Yu** [comment]
The problem should be fixed in version `0.5.2`. Now the build-in node `child_process` max buffer size is removed.

Let me explain a bit more on why the log cannot be processed line by line. The main reason is on the identification of log types. If each line is individually processed, there is no way for the parser to know if the log is generated by latex or bibtex or other processes. There are also multi-line log messages.

At least now super large log should be supported. If the problem persists, please reopen this issue.
